# Generated by Django 5.2.12 on 2026-04-28 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('order_details', models.TextField(verbose_name='Что хотите заказать')),
                ('event_date', models.DateField(verbose_name='Дата события')),
                ('reference_image', models.ImageField(blank=True, null=True, upload_to='references/', verbose_name='Фото референс')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('processed', 'Обработано')], default='new', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата заказа')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('category', models.CharField(choices=[('cakes', 'Торты'), ('cupcakes', 'Капкейки'), ('takeaway', 'Десерты на вынос')], max_length=50, verbose_name='Категория')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('weight', models.CharField(max_length=100, verbose_name='Вес/размер')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Фото')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_popular', models.BooleanField(default=False, verbose_name='Популярный товар')),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('category', models.CharField(choices=[('cakes', 'Торты'), ('cupcakes', 'Капкейки'), ('pastries', 'Пирожные'), ('desserts', 'Десерты')], max_length=50, verbose_name='Категория')),
                ('image', models.ImageField(upload_to='portfolio/', verbose_name='Фото')),
                ('description', models.TextField(verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
            ],
        ),
    ]
