# Generated by Django 5.2.12 on 2026-04-28 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Каталог'},
        ),
        migrations.AlterModelOptions(
            name='work',
            options={'verbose_name': 'Работа', 'verbose_name_plural': 'Портфолио'},
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.CharField(help_text='например: 1 кг, 20 см', max_length=100, verbose_name='Вес/размер'),
        ),
        migrations.AlterField(
            model_name='work',
            name='description',
            field=models.TextField(verbose_name='Описание (ингредиенты, особенности)'),
        ),
    ]
