# Generated by Django 5.2.12 on 2026-04-28 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_order_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.AlterModelOptions(
            name='work',
            options={},
        ),
        migrations.AlterField(
            model_name='order',
            name='order_details',
            field=models.TextField(verbose_name='Что заказать'),
        ),
        migrations.AlterField(
            model_name='order',
            name='reference_image',
            field=models.ImageField(blank=True, null=True, upload_to='references/', verbose_name='Референс'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_popular',
            field=models.BooleanField(default=False, verbose_name='Популярный'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.CharField(max_length=100, verbose_name='Вес/размер'),
        ),
        migrations.AlterField(
            model_name='work',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
    ]
